INSERT INTO DEPARTMENT(DEPARTMENT_ID,NAME) VALUES('D101','DEPARTMENT1');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,NAME) VALUES('D102','DEPARTMENT2');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,NAME) VALUES('D103','DEPARTMENT3');

INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME) VALUES('E101','EMPLOYEE1');
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME) VALUES('E102','EMPLOYEE2');

INSERT INTO EMPLOYEE_DEPARTMENT(EMP_ID,DEPT_ID) VALUES('E101','D101');
INSERT INTO EMPLOYEE_DEPARTMENT(EMP_ID,DEPT_ID) VALUES('E101','D102');
INSERT INTO EMPLOYEE_DEPARTMENT(EMP_ID,DEPT_ID) VALUES('E102','D102');
INSERT INTO EMPLOYEE_DEPARTMENT(EMP_ID,DEPT_ID) VALUES('E102','D103');


INSERT INTO PROJECT(PROJECT_ID,DEPARTMENT_ID,PROJECT_NAME) VALUES ('P101','D101','PROJECT11');
INSERT INTO PROJECT(PROJECT_ID,DEPARTMENT_ID,PROJECT_NAME) VALUES('P102','D101','PROJECT21');
INSERT INTO PROJECT(PROJECT_ID,DEPARTMENT_ID,PROJECT_NAME) VALUES ('P101','D102','PROJECT12');
INSERT INTO PROJECT(PROJECT_ID,DEPARTMENT_ID,PROJECT_NAME) VALUES('P102','D102','PROJECT22');
INSERT INTO PROJECT(PROJECT_ID,DEPARTMENT_ID,PROJECT_NAME) VALUES('P103','D103','PROJECT33');

INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P101','D101','E101');
INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P102','D101','E101');
INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P101','D102','E101');
INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P101','D102','E102');
INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P102','D102','E102');
INSERT INTO EMPLOYEE_PROJECT(PROJECT_ID,DEPT_ID,EMP_ID) VALUES ('P103','D103','E102');

